# Generated by Django 4.2.18 on 2025-02-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsWithModel', '0003_review_city_review_role_review_sign_on_review_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='sign_on',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='web',
            field=models.CharField(max_length=100),
        ),
    ]
