# Generated by Django 4.2.18 on 2025-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsWithModel', '0004_alter_review_city_alter_review_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('manager', 'Manager'), ('guest', 'Guest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sign_on',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='web',
            field=models.CharField(blank=True, choices=[('apache', 'Apache'), ('nginx', 'Nginx'), ('microsoft IIS', 'Microsoft IIS'), ('litespeed', 'LiteSpeed')], max_length=20, null=True),
        ),
    ]
