# Generated by Django 4.2.18 on 2025-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='image',
            field=models.ImageField(default='Balls', upload_to='universes'),
            preserve_default=False,
        ),
    ]
