# Generated by Django 4.2.18 on 2025-02-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0002_universe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alternateImage',
            field=models.ImageField(null=True, upload_to='characters'),
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default='borrar', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universe',
            name='slug',
            field=models.SlugField(default='placeHolder', unique=True),
            preserve_default=False,
        ),
    ]
