# Generated by Django 4.2.18 on 2025-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_rating_remove_review_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sign_on',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='web',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
