# Generated by Django 4.2.18 on 2025-01-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_rol_review_sign_on_review_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rol',
            new_name='role',
        ),
    ]
