# Generated by Django 4.2.18 on 2025-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alternateImage',
            field=models.ImageField(blank=True, upload_to='characters'),
        ),
    ]
